import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const db=new PGlite();
const repo=fileURLToPath(new URL('../../',import.meta.url));
await db.exec(`create role anon;create role authenticated;create schema auth;create schema extensions;
 create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}',email text);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
 grant usage on schema public,auth to authenticated,anon;`);
await db.exec((await readFile(`${repo}/supabase/migrations/01_create_android_schema.sql`,'utf8')).replace('create extension if not exists pgcrypto with schema extensions;',''));
const migration=await readFile(`${repo}/supabase/migrations/06_item_catalog_inventory.sql`,'utf8');
const seed=await readFile(`${repo}/supabase/migrations/07_seed_item_catalog.sql`,'utf8');
await db.exec(migration);await db.exec(migration);await db.exec(seed);await db.exec(seed);
assert.equal((await db.query('select count(*)::int as n from catalog_items')).rows[0].n,236);
const uid=n=>'00000000-0000-0000-0000-'+String(n).padStart(12,'0');
for(const n of [1,2,3])await db.query('insert into auth.users(id,email) values($1,$2)',[uid(n),`test${n}@example.invalid`]);
await db.query("update user_profiles set role='dm' where user_id=$1",[uid(3)]);
for(const n of [1,2])await db.query("insert into trainers(id,owner_id,trainer_name,legacy_name,sheet_data) values($1,$2,$3,$3,$4)",[uid(10+n),uid(n),'Trainer '+n,JSON.stringify({bag:{items_left:['Legacy potion x3']},hp:5})]);
const originals=(await db.query('select id,sheet_data from trainers order by id')).rows;
const catalog=(await db.query('select * from catalog_items order by id')).rows;
const first=catalog.find(i=>i.sprite_path),second=catalog.find(i=>i.id!==first.id);
const login=async(n,role='authenticated')=>{await db.exec('reset role');await db.query("select set_config('test.uid',$1,false)",[n?uid(n):'']);await db.exec(`set role ${role}`);};
let checks=0;
async function denied(fn,code){await assert.rejects(fn,e=>!code||e.code===code);checks++;}
const save=async(o={})=>{const p={trainer:uid(11),key:'left_1',rev:0,item:first.id,free:'',qty:1,notes:'',name:null,description:null,effect:null,...o};
 return (await db.query('select * from save_inventory_slot($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',Object.values(p))).rows[0];};
const edit=async(rev=1,restore=false)=> (await db.query('select * from update_catalog_item($1,$2,$3,$4,$5,$6,$7)',[first.id,rev,'Campaign item','Campaign description','Campaign effect','3',restore])).rows[0];
const create=async(name='DM Amulet',id=uid(50),icon=first.id)=> (await db.query('select * from create_catalog_item($1,$2,$3,$4,$5,$6,$7)',[id,name,'Custom','Story','Heal 4','10',icon])).rows[0];
await login(0,'anon');await denied(()=>db.query('select * from catalog_items'),'42501');await denied(()=>save(),'42501');await denied(()=>create(),'42501');
await login(1);assert.equal((await db.query('select * from catalog_items')).rows.length,236);
await denied(()=>edit(),'42501');await denied(()=>create(),'42501');
await denied(()=>db.query("update catalog_items set custom_effect='hack'"),'42501');
await denied(()=>db.query("insert into trainer_inventory(trainer_id,slot_key) values($1,'left_1')",[uid(11)]),'42501');
let slot=await save();assert.equal(slot.revision,1);
await denied(()=>save(),'40001');await denied(()=>save({rev:1,name:'Hack'}),'42501');
for(const changes of [{key:'left_16'},{qty:-1},{qty:10000},{item:'missing'},{free:'x'.repeat(201)}])await denied(()=>save({rev:1,...changes}));
await login(2);assert.equal((await db.query('select * from trainer_inventory')).rows.length,0);await denied(()=>save({rev:1}),'42501');
await login(3);assert.equal((await db.query('select * from trainer_inventory')).rows.length,1);
slot=await save({rev:1,name:'Unique Potion',description:'Personalized',effect:'Heal 8'});assert.equal(slot.revision,2);
const edited=await edit();assert.equal(edited.custom_effect,'Campaign effect');assert.equal(edited.effect,first.effect);
await denied(()=>edit(),'40001');
const custom=await create();assert(custom.is_custom);assert.equal(custom.sprite_path,first.sprite_path);assert.equal(custom.effect,'Heal 4');
assert.equal((await create()).id,custom.id);await denied(()=>create('Changed payload'),'40001');
await denied(()=>create('  ',uid(51)));await denied(()=>create('Thing',uid(51),'missing'));
assert.equal((await create('No icon',uid(52),null)).sprite_path,null);
await login(1);slot=await save({rev:2,qty:5,notes:'Updated by player'});
assert.equal(slot.custom_name,'Unique Potion');assert.equal(slot.custom_effect,'Heal 8');assert.equal(slot.quantity,5);
await login(3);slot=await save({rev:3,name:'Unique Potion',description:'Personalized',effect:''});assert.equal(slot.custom_effect,'');
await login(1);slot=await save({rev:4,qty:3});assert.equal(slot.custom_effect,'');
slot=await save({rev:5,item:custom.id,qty:1});assert.equal(slot.item_id,custom.id);assert.equal(slot.custom_effect,null);
await login(3);await save({rev:6,item:custom.id,name:'Per specimen',effect:'One-off'});
slot=await save({rev:7,item:custom.id});assert.equal(slot.custom_name,null);assert.equal(slot.custom_effect,null);
slot=await save({rev:8,item:null,qty:0});assert.equal(slot.revision,9);assert.equal(slot.item_id,null);assert.equal(slot.free_text,'');
const restored=await edit(2,true);assert.equal(restored.custom_effect,null);assert.deepEqual(restored.original_data,first.original_data);
await edit(3);await db.exec('reset role');await db.exec(seed);
assert.equal((await db.query('select custom_effect from catalog_items where id=$1',[first.id])).rows[0].custom_effect,'Campaign effect');
assert.equal((await db.query('select count(*)::int as n from catalog_items')).rows[0].n,238);
assert.deepEqual((await db.query('select id,sheet_data from trainers order by id')).rows,originals);
assert.equal((await db.query('select count(*)::int as n from trainer_inventory')).rows[0].n,1);
console.log(`OK item SQL: ${checks} rejected unauthorized/invalid/conflicting operations; seed 236 + 2 custom; owner/DM reads and writes; retry idempotence; overrides and reset; revisions; preserved legacy; repeatable seed/schema. Local PostgreSQL only.`);
const sprites=await readFile(`${repo}/supabase/migrations/08_add_item_sprites.sql`,'utf8');
const beforeSprites=(await db.query('select id,effect,custom_effect,original_data from catalog_items order by id')).rows;
await db.exec(sprites);
assert.equal((await db.query('select count(*)::int as n from catalog_items where not is_custom and sprite_path is not null')).rows[0].n,206);
assert.equal((await db.query("select sprite_path from catalog_items where id='pokedex'")).rows[0].sprite_path,'community/pokedex.png');
const applied=(await db.query('select * from catalog_items order by id')).rows;
await db.exec(sprites);assert.deepEqual((await db.query('select * from catalog_items order by id')).rows,applied);
assert.deepEqual((await db.query('select id,effect,custom_effect,original_data from catalog_items order by id')).rows,beforeSprites);
await db.query("update catalog_items set sprite_path='my-custom-sprite.png' where id='pokedex'");
await db.exec(sprites);
assert.equal((await db.query("select sprite_path from catalog_items where id='pokedex'")).rows[0].sprite_path,'my-custom-sprite.png');
assert.deepEqual((await db.query('select id,sheet_data from trainers order by id')).rows,originals);
console.log('OK sprite migration: 206 baseline items with images; repeatable; customized images and effects preserved; trainer JSON unchanged.');
await db.close();
