import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const repo=fileURLToPath(new URL('../../',import.meta.url));
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;create schema extensions;
 create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}',email text);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
 create table storage.buckets(id text primary key,name text,public boolean default false,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(bucket_id text references storage.buckets(id),name text,primary key(bucket_id,name));
 alter table storage.objects enable row level security;
 grant usage on schema public,auth,storage to authenticated,anon;
 grant select,insert,update,delete on storage.objects to authenticated,anon;
 insert into storage.buckets(id,name,public) values('pokerole-media','pokerole-media',false),('other','other',false);
 create policy legacy_other_bucket on storage.objects for all to authenticated using(bucket_id='other') with check(bucket_id='other');`);
await db.exec((await readFile(`${repo}/supabase/migrations/01_create_android_schema.sql`,'utf8')).replace('create extension if not exists pgcrypto with schema extensions;',''));
await db.exec(await readFile(`${repo}/supabase/migrations/06_item_catalog_inventory.sql`,'utf8'));
await db.exec(await readFile(`${repo}/supabase/migrations/07_seed_item_catalog.sql`,'utf8'));
const before=(await db.query('select * from catalog_items order by id')).rows;
const migration=await readFile(`${repo}/supabase/migrations/09_configure_item_image_storage.sql`,'utf8');
await db.exec(migration);await db.exec(migration);
const bucket=(await db.query("select * from storage.buckets where id='pokerole-items'")).rows[0];
assert.equal(bucket.public,true);assert.equal(Number(bucket.file_size_limit),2097152);
assert.deepEqual(bucket.allowed_mime_types,['image/png','image/jpeg','image/webp']);
assert.equal((await db.query("select public from storage.buckets where id='pokerole-media'")).rows[0].public,false);
assert.deepEqual((await db.query('select * from catalog_items order by id')).rows.map(({custom_image_path,...row})=>row),before);
const uid=n=>'00000000-0000-0000-0000-'+String(n).padStart(12,'0');
for(const n of [1,2])await db.query('insert into auth.users(id,email) values($1,$2)',[uid(n),`test${n}@example.invalid`]);
await db.query("update user_profiles set role='dm' where user_id=$1",[uid(2)]);
const login=async(n,role='authenticated')=>{await db.exec('reset role');await db.query("select set_config('test.uid',$1,false)",[n?uid(n):'']);await db.exec(`set role ${role}`);};
let rejected=0;async function denied(fn){await assert.rejects(fn);rejected++;}
const upload=(path,bucket='pokerole-items')=>db.query('insert into storage.objects(bucket_id,name) values($1,$2)',[bucket,path]);
await login(1);await denied(()=>upload('oggetti/amuleto.png'));
await upload('unchanged.png','other'); // unrelated bucket access preserved
await login(2);await upload('oggetti/amuleto.png');await upload('icons/test.JPG');await upload('icons/test.webp');
await db.query("update storage.objects set name='oggetti/amuleto-v2.png' where bucket_id='pokerole-items' and name='oggetti/amuleto.png'");
assert.equal((await db.query("select * from storage.objects where bucket_id='pokerole-items'")).rows.length,3);
for(const path of ['../file.png','icons/file.svg','https://example.com/image.png','icons/two words.png','icons/a.exe'])await denied(()=>upload(path));
await db.query("delete from storage.objects where bucket_id='pokerole-items' and name='icons/test.JPG'");
await login(1);
assert.equal((await db.query("select * from storage.objects where bucket_id='pokerole-items'")).rows.length,0);
assert.equal((await db.query("delete from storage.objects where bucket_id='pokerole-items' returning *")).rows.length,0);
await denied(()=>db.query("update catalog_items set custom_image_path='icons/test.webp' where id='potion'"));
// Even broad legacy policies cannot override the restrictive DM/anonymous guards.
await db.exec('reset role');await db.exec('create policy broad_legacy on storage.objects for all to authenticated,anon using(true) with check(true)');
await login(1);await denied(()=>upload('bypass.png'));
assert.equal((await db.query("update storage.objects set name='stolen.png' where bucket_id='pokerole-items' returning *")).rows.length,0);
await login(0,'anon');await denied(()=>upload('bypass.png'));
assert.equal((await db.query("select * from storage.objects where bucket_id='pokerole-items'")).rows.length,0);
await db.exec('reset role');
await db.query("update catalog_items set custom_image_path='oggetti/amuleto-v2.png' where id='potion'");
for(const path of ['', '../file.png','https://example.com/image.png','icons/file.svg'])await denied(()=>db.query("update catalog_items set custom_image_path=$1 where id='potion'",[path]));
await db.exec(migration);
assert.equal((await db.query("select custom_image_path from catalog_items where id='potion'")).rows[0].custom_image_path,'oggetti/amuleto-v2.png');
await db.query("update catalog_items set custom_image_path=null where id='potion'");
// Image-edit RPC and revision handling; run against a local PostgreSQL instance only.
const editing=await readFile(`${repo}/supabase/migrations/10_edit_custom_item_images.sql`,'utf8');
await db.exec(editing);await db.exec(editing);
const baseItem=(await db.query("select * from catalog_items where id='potion'")).rows[0];
const filesBefore=(await db.query('select * from storage.objects order by bucket_id,name')).rows;
const setImage=async(id,rev,mode='upload',path='icons/test.webp',source=null)=>(await db.query('select * from set_custom_item_image($1,$2,$3,$4,$5)',[id,rev,mode,path,source])).rows[0];
await login(1);await denied(()=>setImage('potion',baseItem.revision));
await login(0,'anon');await denied(()=>setImage('potion',baseItem.revision));
await login(2);
let standard=await setImage('potion',baseItem.revision);
assert.equal(standard.custom_image_path,'icons/test.webp');assert.equal(standard.sprite_path,baseItem.sprite_path);
assert.equal(standard.effect,baseItem.effect);assert.deepEqual(standard.original_data,baseItem.original_data);
await denied(()=>setImage('potion',baseItem.revision));
await denied(()=>setImage('potion',standard.revision,'sprite',null,'leek'));
for(const path of ['missing.png','../invalid.png','https://example.com/image.png',''])await denied(()=>setImage('potion',standard.revision,'upload',path));
await denied(()=>setImage('potion',standard.revision,'invalid'));await denied(()=>setImage('potion',standard.revision,null));
const createImageItem=async(id,name)=>(await db.query('select * from create_catalog_item($1,$2,$3,$4,$5,$6,$7)',[uid(id),name,'Custom','Description','Special effect','10','potion'])).rows[0];
let custom=await createImageItem(51,'Amulet');
assert.equal(custom.custom_image_path,standard.custom_image_path);assert.equal(custom.original_data.CustomImagePath,standard.custom_image_path);
assert.equal((await createImageItem(51,'Amulet')).id,custom.id);
custom=await setImage(custom.id,custom.revision,'upload','oggetti/amuleto-v2.png');
assert.equal(custom.custom_image_path,'oggetti/amuleto-v2.png');assert.equal(custom.effect,'Special effect');
custom=await setImage(custom.id,custom.revision,'sprite',null,'super-potion');
assert.equal(custom.sprite_path,'super-potion.png');assert.equal(custom.custom_image_path,null);
custom=await setImage(custom.id,custom.revision,'reset',null);
assert.equal(custom.sprite_path,baseItem.sprite_path);assert.equal(custom.custom_image_path,'icons/test.webp');
standard=await setImage('potion',standard.revision,'reset',null);
assert.equal(standard.custom_image_path,null);assert.equal(standard.sprite_path,baseItem.sprite_path);
await db.exec('reset role');
await db.query("update catalog_items set custom_image_path='icons/test.webp' where id='potion'");
assert.equal((await db.query("select revision from catalog_items where id='potion'")).rows[0].revision,standard.revision+1);
await login(2);await denied(()=>setImage('potion',standard.revision));
await db.exec('reset role');
assert.deepEqual((await db.query('select * from storage.objects order by bucket_id,name')).rows,filesBefore);
console.log('OK image editing: DM upload all items, custom-only sprite selection, original reset, preserved effects/files, stale editor rejection, dashboard revision, creation copies image.');
// Refuse to publish a populated private bucket; the existing files must remain private.
await db.exec("update storage.buckets set public=false where id='pokerole-items'");
await denied(()=>db.exec(migration));await db.exec('rollback');
assert.equal((await db.query("select public from storage.buckets where id='pokerole-items'")).rows[0].public,false);
console.log(`OK item image storage: ${rejected} rejected writes/invalid paths; bucket and column repeatable; DM-only writes despite broad policies; media bucket and item data preserved. Storage HTTP uploads/public downloads not tested locally.`);
await db.close();
