"""Generate the versioned Supabase Ability catalog migration from Android assets."""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = ROOT / "android-app/app/src/main/assets/pokerole/abilities-v3.json"
RULES_VERSION = "3.0"
EXPECTED_COUNT = 305
EXPECTED_KEYS = {"_id", "Name", "Description", "Effect"}
ID_PATTERN = re.compile(r"^[a-z0-9]+(?:[-'][a-z0-9]+)*$")


@dataclass(frozen=True, slots=True)
class Ability:
    ability_id: str
    name: str
    description: str
    effect: str
    filename: str


def _required_text(payload: dict[str, object], key: str, filename: str) -> str:
    value = payload.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{filename}: {key} must be a non-empty string")
    return value


def _source_payloads(source: Path) -> list[tuple[str, dict[str, object]]]:
    if source.is_file():
        payload = json.loads(source.read_text(encoding="utf-8"))
        if not isinstance(payload, list):
            raise ValueError(f"{source}: top-level JSON value must be an array")
        rows: list[tuple[str, dict[str, object]]] = []
        for index, row in enumerate(payload):
            if not isinstance(row, dict):
                raise ValueError(f"{source.name}[{index}]: Ability must be an object")
            rows.append((f"{source.name}[{index}]", row))
        return rows

    paths = sorted(source.glob("*.json"), key=lambda path: path.name.casefold())
    if not paths:
        raise ValueError(f"No Ability JSON source found at {source}")
    rows = []
    for path in paths:
        payload = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(payload, dict):
            raise ValueError(f"{path.name}: top-level JSON value must be an object")
        rows.append((path.name, payload))
    return rows


def load_abilities(source: Path) -> list[Ability]:
    source_rows = _source_payloads(source)

    abilities: list[Ability] = []
    ids: dict[str, str] = {}
    names: dict[str, str] = {}
    for filename, payload in source_rows:
        if set(payload) != EXPECTED_KEYS:
            raise ValueError(
                f"{filename}: expected keys {sorted(EXPECTED_KEYS)}, got {sorted(payload)}"
            )

        ability_id = _required_text(payload, "_id", filename)
        name = _required_text(payload, "Name", filename)
        description = _required_text(payload, "Description", filename)
        effect = _required_text(payload, "Effect", filename)
        if not ID_PATTERN.fullmatch(ability_id):
            raise ValueError(f"{filename}: invalid stable ID {ability_id!r}")

        normalized_id = ability_id.casefold()
        normalized_name = name.strip().casefold()
        if normalized_id in ids:
            raise ValueError(f"Duplicate ID {ability_id!r}: {ids[normalized_id]}, {filename}")
        if normalized_name in names:
            raise ValueError(
                f"Duplicate normalized name {name!r}: {names[normalized_name]}, {filename}"
            )
        ids[normalized_id] = filename
        names[normalized_name] = filename
        abilities.append(Ability(ability_id, name, description, effect, filename))

    if len(abilities) != EXPECTED_COUNT:
        raise ValueError(
            f"Ability source must contain exactly {EXPECTED_COUNT} definitions, got {len(abilities)}"
        )

    return sorted(abilities, key=lambda ability: ability.ability_id)


def _sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def render_migration(abilities: list[Ability], source: Path) -> str:
    values = ",\n".join(
        "    ("
        + ", ".join(
            _sql_literal(value)
            for value in (
                RULES_VERSION,
                ability.ability_id,
                ability.name,
                ability.description,
                ability.effect,
            )
        )
        + ")"
        for ability in abilities
    )
    source_label = source.relative_to(ROOT).as_posix()
    count = len(abilities)
    return f"""-- Generated by scripts/generate_ability_catalog_migration.py.
-- Source: {source_label} ({count} Ability definitions, PokéRole rules {RULES_VERSION}).
-- Regenerate; do not hand-edit the seed rows below.

begin;

alter table public.catalog_sources
    add column if not exists ability_count integer;

create table if not exists public.catalog_abilities (
    rules_version text not null references public.catalog_sources(rules_version),
    id text not null,
    name text not null,
    description text not null,
    effect text not null,
    name_key text generated always as (lower(btrim(name))) stored,
    primary key (rules_version, id),
    constraint catalog_abilities_rules_version_name_key unique (rules_version, name),
    constraint catalog_abilities_id_check check (btrim(id) <> ''),
    constraint catalog_abilities_name_check check (btrim(name) <> ''),
    constraint catalog_abilities_description_check check (btrim(description) <> ''),
    constraint catalog_abilities_effect_check check (btrim(effect) <> '')
);

create unique index if not exists catalog_abilities_rules_version_normalized_name_key
    on public.catalog_abilities (rules_version, name_key);

alter table public.catalog_abilities enable row level security;
drop policy if exists catalog_authenticated_read on public.catalog_abilities;
create policy catalog_authenticated_read
    on public.catalog_abilities for select to authenticated using (true);

revoke all on table public.catalog_abilities from public, anon, authenticated;
grant select on table public.catalog_abilities to authenticated;

create temporary table ability_seed (
    rules_version text not null,
    id text not null,
    name text not null,
    description text not null,
    effect text not null
) on commit drop;

insert into ability_seed (rules_version, id, name, description, effect) values
{values};

do $$
begin
    if (select count(*) from ability_seed) <> {count} then
        raise exception 'Ability seed count differs from the {count} source files';
    end if;
    if exists (
        select 1 from ability_seed
        where btrim(id) = '' or btrim(name) = ''
           or btrim(description) = '' or btrim(effect) = ''
    ) then
        raise exception 'Ability seed contains blank required fields';
    end if;
    if exists (
        select 1 from ability_seed
        group by rules_version, id having count(*) > 1
    ) then
        raise exception 'Ability seed contains duplicate IDs';
    end if;
    if exists (
        select 1 from ability_seed
        group by rules_version, lower(btrim(name)) having count(*) > 1
    ) then
        raise exception 'Ability seed contains normalized-name collisions';
    end if;
end;
$$;

delete from public.catalog_abilities as existing
where existing.rules_version = {_sql_literal(RULES_VERSION)}
  and not exists (
      select 1 from ability_seed
      where ability_seed.rules_version = existing.rules_version
        and ability_seed.id = existing.id
  );

insert into public.catalog_abilities (rules_version, id, name, description, effect)
select rules_version, id, name, description, effect
from ability_seed
on conflict (rules_version, id) do update set
    name = excluded.name,
    description = excluded.description,
    effect = excluded.effect;

update public.catalog_sources
set ability_count = (
    select count(*) from ability_seed
    where ability_seed.rules_version = catalog_sources.rules_version
)
where rules_version = {_sql_literal(RULES_VERSION)};

alter table public.catalog_sources
    alter column ability_count set not null;

alter table public.catalog_sources
    drop constraint if exists catalog_sources_ability_count_check;
alter table public.catalog_sources
    add constraint catalog_sources_ability_count_check check (ability_count >= 0);

do $$
begin
    if (select count(*) from public.catalog_abilities where rules_version = {_sql_literal(RULES_VERSION)}) <> {count} then
        raise exception 'catalog_abilities row count does not match the Ability source';
    end if;
    if exists (
        select rules_version, id, name, description, effect from ability_seed
        except
        select rules_version, id, name, description, effect from public.catalog_abilities
    ) or exists (
        select rules_version, id, name, description, effect from public.catalog_abilities
        where rules_version = {_sql_literal(RULES_VERSION)}
        except
        select rules_version, id, name, description, effect from ability_seed
    ) then
        raise exception 'catalog_abilities differs from the Ability source';
    end if;
end;
$$;

commit;
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    source = args.source.resolve()
    output = args.output.resolve()
    rendered = render_migration(load_abilities(source), source)
    if args.check:
        if not output.exists() or output.read_text(encoding="utf-8") != rendered:
            raise SystemExit(f"Generated migration is out of date: {output}")
        print(f"OK: {output} matches {len(load_abilities(source))} Ability definitions")
        return

    output.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"Wrote {output} from {len(load_abilities(source))} Ability definitions")


if __name__ == "__main__":
    main()
